pcall(require, "luarocks.loader")

local gears = require("gears")
local awful = require("awful")
require("awful.autofocus")
local wibox = require("wibox")
local beautiful = require("beautiful")
local naughty = require("naughty")
local menubar = require("menubar")
local hotkeys_popup = require("awful.hotkeys_popup")
require("awful.hotkeys_popup.keys")

require("config.error")
require("config.variables")
require("config.menu")
require("config.wibar")
require("config.keybinds")
require("config.app-launcher")
require("config.rules")
require("config.signals")
