#!/bin/sh

# NOTE: This script will automatically be run from stage0, inside the chroot

user="${1:-rick}"

# Exit on any error
set -e

# Set time zone
ln -sf /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime

# Set hardware clock
hwclock --systohc

# Set region and language formatting
sed -Ei '
	s/^#(en_US.UTF-8 UTF-8.*)/\1/;
' /etc/locale.gen
locale-gen

# Set locale
echo "LANG=en_US.UTF-8" > /etc/locale.conf

# Set hostname
echo "arch-vm" > /etc/hostname

# Create initramfs
mkinitcpio -P

# Set root password
passwd

# Configure bootloader
mkdir -p /boot/loader/entries
cat << EOF > /boot/loader/loader.conf
timeout 5
default arch
EOF
UUID=$(blkid | sed -nE 's/.*sda2.* PARTUUID="(.*)"/\1/p')
cat << EOF > /boot/loader/entries/arch.conf
title Arch Linux
linux /vmlinuz-linux
initrd /initramfs-linux.img
options root=PARTUUID=$UUID rw
EOF
bootctl install

# Enable networking
ln -sf /dev/null /etc/systemd/network/99-default.link
systemctl enable NetworkManager

# Enable SSD trim
systemctl enable fstrim.timer

# Allow sudo via password
sed -Ei '
	s/^# (%wheel ALL=\(ALL:ALL\) ALL)/\1/;
' /etc/sudoers

# Add user account
useradd -m -G wheel -s /bin/bash "$user"
passwd "$user"
mv /dotfiles "/home/$user"
chown -R "$user:$user" "/home/$user/dotfiles"

# Enable pacman colors
sed -Ei '
	s/^#(Color)/\1/;
' /etc/pacman.conf

# Exit
exit
